parameters:
    blizzard.api.service.class: petrepatrasc\BlizzardApiBundle\Service\ApiService
    blizzard.api.call.service.class: petrepatrasc\BlizzardApiBundle\Service\CallService

services:
    blizzard_api.call_service:
        class: %blizzard.api.call.service.class%

    blizzard_api:
        class: %blizzard.api.service.class%
        arguments: [@blizzard_api.call_service]