language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - composer install -n

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml